### PR TITLE
fix: Fix entity animations.

### LINKED ISSUE #726: Feature Request: Smoother/Less choppy Aechor Plant Animation
### What Feature Types Apply to This Request?

Entity

### Other Type

_No response_

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

The current Aechor Plant animation looks choppy, since it is only updated each tick.

Potentially helpful code from the Aether II (which has a smoother aechor plant animation):
[The Aether II - EntityAechorPlant::tickAnimation](https://github.com/Gilded-Games/The-Aether-II/blob/e838fc8746730ce425ed668281ca0d903fb0ab4f/src/main/java/com/gildedgames/aether/common/entities/monsters/EntityAechorPlant.java#L317-L338)
[The Aether II - RenderAechorPlant::preRenderCallback (sin calculation)](https://github.com/Gilded-Games/The-Aether-II/blob/e838fc8746730ce425ed668281ca0d903fb0ab4f/src/main/java/com/gildedgames/aether/client/renderer/entities/living/RenderAechorPlant.java#L39-L67)

### Why Should It Be in the Mod?

It should be in the mod to make the Aechor Plant's animation look better and less out of place, since every other mob animation in the Aether and Minecraft is smooth.

### Does This Feature Improve Compatibility With Another Mod?

_No response_

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

### LINKED ISSUE #727: Feature Request: More choppy animation fixes
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Rendering/Animations

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Continuation of #726 

Here are some more choppy animations I found:
- Zephyr puffing up before attacking
- Aerbunny hopping animation (rotation and scaling)
- Aerwhale up and down rotation
- Sheepuff wool puffing up (I have not seen this one in-game, but it seems to have the same issue in the code)
- Sheepuff head rotation when looking up and down (This also affects vanilla sheep)

### Why Should It Be in the Mod?

To improve consistency with vanilla animations, which are all smooth

### Does This Feature Improve Compatibility With Another Mod?

_No response_

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

### PR DESCRIPTION
**Pull request by bconlon1**
- [x] Closes #726.
- [x] Closes #727.

### CODE REVIEW

**Comment by Zepalesque** [comment]
The new version of the animation looks better, but I noticed a couple of problems:
- It doesn't pause when minecraft is paused
- If the fps is lower than the monitor's refresh rate, the animation will appear slower
- The movement animation for when the aechor plant is hurt and glows red seems slower than before (this might be intentional, I'm not sure)

**Comment by bconlon1** [comment]
How are you certain of the second point?

**Comment by Zepalesque** [comment]
I had my fps set to a setting lower than my monitor's refresh rate, and the animation was slower, but when I set it to unlimited the animation was fine. I turned it down to 10 fps, and the aechor plant barely moved at all. I also tried turning up the render distance all the way to lag minecraft, and the animation was slower, but kind of wobbly, changing speeds depending on the fps.

**Review by Drullkus — APPROVED** [review]
Nicely done!

**Pull request merged**
