### PR TITLE
Add de_DE.json (German translations)

### PR DESCRIPTION
**Pull request by ZolaKluke**
Contains a de_DE.json with all translations ported from 1.12.2 to the new format as well as adding a few additional translations for new content

### CODE REVIEW

**Comment by ZolaKluke** [comment]
Some lines are still untranslated as they were either not translated in 1.12.2 or my lack of German for new content

**Review by Drullkus — CHANGES_REQUESTED** [review]
You're going to want to relocate this file from ` src/generated/resources/assets/aether/lang/de_DE.json` to ` src/resources/assets/aether/lang/de_DE.json`, otherwise the DataGenerator will delete this because it's in the `generated` directory

**Comment by ZolaKluke** [comment]
Translations have been moved from generated folder to main folder

**Review by Drullkus — APPROVED** [review]
Fantastic!

**Pull request merged**
