### PR TITLE
fix(audio): Certain mob sounds now playback correctly in stereo space

### LINKED ISSUE #793: Bug: Certain in-world sounds are stereo instead of mono
### What Feature Types Apply to This Bug?

Audio

### Other Type

_No response_

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.1.3

### The Aether 1 Version

0.0.1

### Is This Bug a Conflict With Another Mod?

_No response_

### Client Log

_No response_

### Crash Report (if applicable)

_No response_

### Steps to Reproduce

- Trigger any applicable stereo sound in-world (examples listed below). Weather this be through /playsound with an offset, or from original source.
- Look around, or move away from the sound's source while it's playing.

### What You Expect To Happen

The sound should be heard coming from the direction it came, at an applicable volume for whatever played it.

### What Actually Happened

The sound is always full volume, and doesn't appear to originate from any direction.

### Additional Details

This issue is new to 1.14+, after the sound system was rewritten. Only UI, ambience, or music files are typically in stereo (with the exception of records). Things that don't have a specific in-world origin.

**Affected Sounds (all in the `assets/aether/sounds/` directory):**
- entity/aerbunny/hurt
- entity/aerbunny/death
- entity/aerwhale/death
- entity/moa/say
- entity/zephyr/call
- entity/zephyr/shoot

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

### PR DESCRIPTION
**Pull request by saintselect**
```
Affected sound files were mixed-down from stereo to mono. All now behave as-intended when testing via /playsound

Closes #793
```

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Comment by bconlon1** [comment]
Would you be able to state "I agree to the Contributor License Agreement (CLA)." at the end of the description? Otherwise this PR looks pretty good, I just need to trigger the build for it.

**Comment by saintselect** [comment]
Updated the description, hope it's all formatted right.

**Comment by bconlon1** [comment]
The PR is formatted perfectly, I'm actually surprised to see it formatted this way since the contributor guidelines for this are still WIP.

**Comment by saintselect** [comment]
Hahaha. I noticed the more up-to-date WIP guidelines and figured I'd follow those instead, sorry if I jumped the gun too early :grin:

**Review by bconlon1 — APPROVED** [review]
lgtm

**Pull request merged**
