### PR TITLE
1.19.2 fix: missing categories in recipes

### PR DESCRIPTION
**Pull request by Toranktto**
Players can't connect to Aether servers due to:
```
[Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: [...] lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "p_130069_" is null
```

---

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Review by bconlon1 — APPROVED** [review]
lgtm

**Review by bconlon1 — CHANGES_REQUESTED** [review]
actually there seem to be merge conflicts when the build task attempts to build this PR, make sure your branch is up to date with 1.19.2-develop.

**Comment by Toranktto** [comment]
Hmm, it is: https://github.com/Toranktto/The-Aether/commits/fix/recipes

**Comment by bconlon1** [comment]
I'll just merge without build then since the only changes are jsons. I blame git

**Pull request merged**
