### PR TITLE
Optimize block recipe checking to reduce overhead on block updates

### PR DESCRIPTION
**Pull request by shBLOCK**
closes issue #1949
This would make the **block recipes no longer work in dimensions other than the aether**, check the issue for more details.
I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Comment by bconlon1** [comment]
Icestone should still be able to work outside the Aether. I think isolating ban recipes to the Aether is potentially a good solution but i might have to think if theres other ways to avoid that overhead without possibly breaking changes.

**Comment by shBLOCK** [comment]
Most of the overhead comes from biome matching for the ban recipe (for vanilla aether there are not many recipes to match for anyway).
So just adding this dimension check for the ban recipe is already going to get rid of most of the overhead.

**Comment by bconlon1** [comment]
I may be able to fix some of the overhead by other means through caching inputs for more of the block recipes to check that list before getting to the biome check, I'll have to try it out.

**Comment by bconlon1** [comment]
https://github.com/The-Aether-Team/The-Aether/pull/1959 wouldn't this be a better way of making this more performant?

**Comment by shBLOCK** [comment]
> #1959 wouldn't this be a better way of making this more performant?

Oh yeah, I didn't even think of that, that's smart.
It would still cause a biome check if the block being updated is a torch or something, but I think one or two checks are probably fine?
But maybe it would still help to add this dimension check for the ban recipe.

**Comment by bconlon1** [comment]
I would rather not as it would introduce a breaking change. I think this works for now unless people report continued performance issues.

**Pull request closed without merging**
