### PR TITLE
improv: New IS_COLD Damage type for Sun Spirit

### PR DESCRIPTION
**Pull request by darksonic300**
Adds a new DamageType tag `IS_COLD` to the Aether and changes the Sun Spirit damage check accordingly.

- By expanding the invulnerability check to a tag instead of the single Ice Crystal, the Sun Spirit can now take damage by other possible items added by addons or other mods.
- It doesn't change the core functionality and extends possibilities.
- It can be made configurable in case someone doesn't want other damage options.

### CODE REVIEW

**Review by Jonathing — APPROVED** [review]

**Review by bconlon1 — CHANGES_REQUESTED** [review]
Make sure to run datagen after you've added the tag.

**Review by bconlon1 — APPROVED** [review]
lgtm

**Comment by darksonic300** [comment]
Done.

**Review by bconlon1 — APPROVED** [review]
lgtm

**Pull request merged**
