### PR TITLE
OptiFine CTM for Quicksoil glass and Skyroot Bookshelf

### LINKED ISSUE #290: Feature: CTM compatibility
- Connected textures.

### PR DESCRIPTION
**Pull request by Mr-Aerod**
- [x] Closes #290.

### CODE REVIEW

**Review by bconlon1 — CHANGES_REQUESTED** [review]
- CTM connected textures are using the wrong path; they should be using the Aether location not Minecraft's.
- Optifine connected textures don't work in-game as far as I can tell (are you sure Optifine connected textures work for mod blocks? There's a reason we didn't do them for 1.12 which is that Optifine didn't support this; I'm not sure if that's been fixed).
- Programmer Art equivalents are needed for the connected textures.

**Comment by Mr-Aerod** [comment]
Even though I found the bug report on OptiFine's side still unresolved, luckily there was this comment in the bottom of the page. Posting it here for when I'm gonna fix it (probably tomorrow), so I have it saved and accessible somewhere.

**Comment by Mr-Aerod** [comment]
I got to test it in game for the first time (I made it a resource pack so I hope this works when in the mod directory too): I probably won't be moving the optifine ctm folder into the Aether directory because OptiFine textures only work for me when the ctm is located in the minecraft directory, not the Aethers. However, ConnectedTexturesMod's textures don't quiite work..

**Comment by Mr-Aerod** [comment]
I'm not sure if I'll be able to get the CTM mod's ctm working. Every time I change the Quicksoil Glass render type to translucent and try to reload the pack, it just crashes my game.

**Comment by Mr-Aerod** [comment]
I'll remove the CTM's ctm textures for now, and will only focus on OptiFine ones.

**Review by bconlon1 — APPROVED** [review]
lgtm

**Pull request merged**
