### PR TITLE
feat: CraftTweaker compatibility for fuel editing

### LINKED ISSUE #288: Feature: CraftTweaker compatibility.
- [x] Reimplement CraftTweaker in gradle to the 1.19 branch.
- [x] Removing and adding custom fuels.

### PR DESCRIPTION
**Pull request by bconlon1**
closes #288

### CODE REVIEW

**Comment by bconlon1** [comment]
Documentation: https://github.com/CraftTweaker/CraftTweaker-Documentation/pull/549

**Comment by jaredlll08** [comment]
In general we (CraftTweaker) generally ask mods to not add new globals, as it will cause issues if 2 mods try and use the `altar` global.

My recommendation would be to instead make the methods static and have a static call like so:
```zenscript
mods.aether.AltarFuelManager.addFuel(<item:minecraft:dirt>, 200);
```

**Comment by bconlon1** [comment]
Updated methods to be static and removed globals accordingly.

**Review by OzPayn — APPROVED** [review]
should be good to merge

**Pull request merged**
