### PR TITLE
fix: smelting speed

### PR DESCRIPTION
**Pull request by bconlon1**
#2306

### CODE REVIEW

**Review by OzPayn — APPROVED** [review]
smelt speed rejuvenated

**Comment by BabylonAS** [comment]
Am I right to interpret the change as if the 2× smelting speed for the items affected by https://github.com/The-Aether-Team/The-Aether/issues/2306 was not intentional in the first place?

**Comment by bconlon1** [comment]
Speed for smelting is 200 while blasting is 100

**Comment by BabylonAS** [comment]
Yeah, that's how it's set for vanilla items. But when I first noticed the smelting speed quirk I thought the Aether deliberately had the “small” items like rings, necklaces, and medals smelt faster than all others. I assumed it was a feature, a neat usage of Minecraft's data pack based customizability, and the apparent bug was that the blasting speed wasn't increased in the same way. I didn't think it was the other way around.

The higher speed could make a bit less sense with gloves, but, on the other hand, a ring requires twice as many ingots. But, if the intent was to never have faster smelting for these items, then oh well.

**Pull request merged**
