### PR TITLE
[1.18]add swet shrink animation

### PR DESCRIPTION
**Pull request by baguchi**
I add swet shrink animation like aether 2 in 1.18(Same as #295 )
when swet is shrink It also weakens the power to launch the player
146841230-eb5aebc7-cf5c-4429-9969-0b08799250c4

### CODE REVIEW

**Review by Drullkus — CHANGES_REQUESTED** [review]
Do you have a video of the shrinking in action?

**Comment by baguchi** [comment]
yep. here is
https://user-images.githubusercontent.com/88538210/148667824-8f09b924-f8bd-489d-9a49-cc732fc52441.mp4

**Review by bconlon1 — CHANGES_REQUESTED** [review]
Based on Aether I behavior, Swets are meant to die/completely dissolve when they go in water. I think having them shrink in some way would be fine to incorporate into their death animation, but having them survive and shrink is inconsistent with the original mod's design.

**Comment by baguchi** [comment]
I fixed swet code and completely dissolve in the water
https://user-images.githubusercontent.com/88538210/149257154-18846419-0191-409c-86d8-970be96dcbea.mp4

**Review by Burning-Cactus — APPROVED** [review]
Looks good to me!

**Review by Burning-Cactus — APPROVED** [review]

**Review by Burning-Cactus — APPROVED** [review]

**Review by bconlon1 — APPROVED** [review]

**Review by Drullkus — APPROVED** [review]

**Pull request merged**
