### PR TITLE
improv: Berry Bushes now work with fast graphics

### PR DESCRIPTION
**Pull request by bconlon1**
#2096

### CODE REVIEW

**Comment by mrjasonn** [comment]
Just a quick question: does this just datagen a fixed texture image file?

**Comment by bconlon1** [comment]
This PR has changed texture files, changed datagenned models, and a new model class registered in the file diff.

**Review by OzPayn — APPROVED** [review]
lgtm

**Comment by mrjasonn** [comment]
> This PR has changed texture files, changed datagenned models, and a new model class registered in the file diff.

What does the new model class do? @bconlon1

**Pull request merged**
