### PR TITLE
feat: Config for Invisibility Cloak particles

### LINKED ISSUE #1360: Enhancement: Invisibility Cloak Balancing
- Config to make it not completely de-render armor?
- Temporarily de-render armor during attacks?
- Make other mobs aggro if you attack one nearby others.

### PR DESCRIPTION
**Pull request by bconlon1**

### CODE REVIEW

**Review by Jonathing — CHANGES_REQUESTED** [review]
Make it a server config.

i love trolling

**Review by Jonathing — CHANGES_REQUESTED** [review]
[Discussion on Discord](https://discord.com/channels/118816101936267265/569972352373358653/1111076872135127102)

**Comment by bconlon1** [comment]
Going to have to discuss better solutions internally so I am just going to close this PR and make another one later on.

**Comment by Jonathing** [comment]
Thank fuck, you can finally fix our blasted server configs 🙏🙏🙏🙏🙏🙏🙏

**Pull request closed without merging**
